![](logo.png)

# <font color='red'>R Dataframes</font>

> ### R Dataframe Basics
> ### R Dataframe Indexing and Selections
> ### Merging R Dataframes
> ### R Lists

We've learned about R vectors and two-dimensional R matrices. Now we're going to learn about R Dataframes, which are one of the main tools for data analysis with R. Matrix inputs are limited bercause all of the data inside of the matrix had to be of the same data type (numeric, character, logicals, etc.). R Dataframes can be organized with mixed data types to create a very powerful data structure.

# <font color='red'>R Dataframe Basics</font>

R actually has built-in Dataframes for a quick reference for learning about these data structures.

## Built-in R Dataframes

In [141]:
# Dataframe about states
state.x77

Population Income Illiteracy Life Exp Murder HS Grad Frost
Alabama         3615      3624   2.1        69.05    15.1   41.3     20  
Alaska           365      6315   1.5        69.31    11.3   66.7    152  
Arizona         2212      4530   1.8        70.55     7.8   58.1     15  
Arkansas        2110      3378   1.9        70.66    10.1   39.9     65  
California     21198      5114   1.1        71.71    10.3   62.6     20  
Colorado        2541      4884   0.7        72.06     6.8   63.9    166  
Connecticut     3100      5348   1.1        72.48     3.1   56.0    139  
Delaware         579      4809   0.9        70.06     6.2   54.6    103  
Florida         8277      4815   1.3        70.66    10.7   52.6     11  
Georgia         4931      4091   2.0        68.54    13.9   40.6     60  
Hawaii           868      4963   1.9        73.60     6.2   61.9      0  
Idaho            813      4119   0.6        71.87     5.3   59.5    126  
Illinois       11197      5107   0.9        70.14    10.3   52.6    127  
Indiana         5313      4458   0.7        70.88     7.1   52.9    122  
Iowa            2861      4628   0.5        72.56     2.3   59.0    140  
Kansas          2280      4669   0.6        72.58     4.5   59.9    114  
Kentucky        3387      3712   1.6        70.10    10.6   38.5     95  
Louisiana       3806      3545   2.8        68.76    13.2   42.2     12  
Maine           1058      3694   0.7        70.39     2.7   54.7    161  
Maryland        4122      5299   0.9        70.22     8.5   52.3    101  
Massachusetts   5814      4755   1.1        71.83     3.3   58.5    103  
Michigan        9111      4751   0.9        70.63    11.1   52.8    125  
Minnesota       3921      4675   0.6        72.96     2.3   57.6    160  
Mississippi     2341      3098   2.4        68.09    12.5   41.0     50  
Missouri        4767      4254   0.8        70.69     9.3   48.8    108  
Montana          746      4347   0.6        70.56     5.0   59.2    155  
Nebraska        1544      4508   0.6        72.60     2.9   59.3    139  
Nevada           590      5149   0.5        69.03    11.5   65.2    188  
New Hampshire    812      4281   0.7        71.23     3.3   57.6    174  
New Jersey      7333      5237   1.1        70.93     5.2   52.5    115  
New Mexico      1144      3601   2.2        70.32     9.7   55.2    120  
New York       18076      4903   1.4        70.55    10.9   52.7     82  
North Carolina  5441      3875   1.8        69.21    11.1   38.5     80  
North Dakota     637      5087   0.8        72.78     1.4   50.3    186  
Ohio           10735      4561   0.8        70.82     7.4   53.2    124  
Oklahoma        2715      3983   1.1        71.42     6.4   51.6     82  
Oregon          2284      4660   0.6        72.13     4.2   60.0     44  
Pennsylvania   11860      4449   1.0        70.43     6.1   50.2    126  
Rhode Island     931      4558   1.3        71.90     2.4   46.4    127  
South Carolina  2816      3635   2.3        67.96    11.6   37.8     65  
South Dakota     681      4167   0.5        72.08     1.7   53.3    172  
Tennessee       4173      3821   1.7        70.11    11.0   41.8     70  
Texas          12237      4188   2.2        70.90    12.2   47.4     35  
Utah            1203      4022   0.6        72.90     4.5   67.3    137  
Vermont          472      3907   0.6        71.64     5.5   57.1    168  
Virginia        4981      4701   1.4        70.08     9.5   47.8     85  
Washington      3559      4864   0.6        71.72     4.3   63.5     32  
West Virginia   1799      3617   1.4        69.48     6.7   41.6    100  
Wisconsin       4589      4468   0.7        72.48     3.0   54.5    149  
Wyoming          376      4566   0.6        70.29     6.9   62.9    173  
               Area  
Alabama         50708
Alaska         566432
Arizona        113417
Arkansas        51945
California     156361
Colorado       103766
Connecticut      4862
Delaware         1982
Florida         54090
Georgia         58073

In [142]:
# US personal expense
USPersonalExpenditure

1940   1945   1950  1955 1960 
Food and Tobacco    22.200 44.500 59.60 73.2 86.80
Household Operation 10.500 15.500 29.00 36.5 46.20
Medical and Health   3.530  5.760  9.71 14.0 21.10
Personal Care        1.040  1.980  2.45  3.4  5.40
Private Education    0.341  0.974  1.80  2.6  3.64

In [143]:
# Women
women

height weight
1  58     115   
2  59     117   
3  60     120   
4  61     123   
5  62     126   
6  63     129   
7  64     132   
8  65     135   
9  66     139   
10 67     142   
11 68     146   
12 69     150   
13 70     154   
14 71     159   
15 72     164

Use the built-in R Function **data()** to get a list of all available built-in R Dataframes

In [144]:
# List of built-in R Dataframes
data()

## Working with Dataframes

If you noticed, the states dataframe is large. Use the built-in R functions **head()** and **tail()** to view the first and last six rows, respectively.

In [145]:
# Quick variable assignment for shortcut
states <- state.x77

In [146]:
head(states)

Population Income Illiteracy Life Exp Murder HS Grad Frost Area  
Alabama     3615      3624   2.1        69.05    15.1   41.3     20    50708
Alaska       365      6315   1.5        69.31    11.3   66.7    152   566432
Arizona     2212      4530   1.8        70.55     7.8   58.1     15   113417
Arkansas    2110      3378   1.9        70.66    10.1   39.9     65    51945
California 21198      5114   1.1        71.71    10.3   62.6     20   156361
Colorado    2541      4884   0.7        72.06     6.8   63.9    166   103766

In [147]:
tail(states)

Population Income Illiteracy Life Exp Murder HS Grad Frost Area 
Vermont        472       3907   0.6        71.64    5.5    57.1    168    9267
Virginia      4981       4701   1.4        70.08    9.5    47.8     85   39780
Washington    3559       4864   0.6        71.72    4.3    63.5     32   66570
West Virginia 1799       3617   1.4        69.48    6.7    41.6    100   24070
Wisconsin     4589       4468   0.7        72.48    3.0    54.5    149   54464
Wyoming        376       4566   0.6        70.29    6.9    62.9    173   97203

## Dataframes - Overview of Information

Use the built-in R function **str()** to get the structure of a Dataframe, which gives information on the structure of the dataframe and the data contained - including variable names and data types. Use the built-in R function **summary()** to get a quick statistical summary of all of the columns of a Dataframe, depending on the data, this could be very useful

In [148]:
# Statistical summary of data
summary(states)

   Population        Income       Illiteracy       Life Exp    
 Min.   :  365   Min.   :3098   Min.   :0.500   Min.   :67.96  
 1st Qu.: 1080   1st Qu.:3993   1st Qu.:0.625   1st Qu.:70.12  
 Median : 2838   Median :4519   Median :0.950   Median :70.67  
 Mean   : 4246   Mean   :4436   Mean   :1.170   Mean   :70.88  
 3rd Qu.: 4968   3rd Qu.:4814   3rd Qu.:1.575   3rd Qu.:71.89  
 Max.   :21198   Max.   :6315   Max.   :2.800   Max.   :73.60  
     Murder          HS Grad          Frost             Area       
 Min.   : 1.400   Min.   :37.80   Min.   :  0.00   Min.   :  1049  
 1st Qu.: 4.350   1st Qu.:48.05   1st Qu.: 66.25   1st Qu.: 36985  
 Median : 6.850   Median :53.25   Median :114.50   Median : 54277  
 Mean   : 7.378   Mean   :53.11   Mean   :104.46   Mean   : 70736  
 3rd Qu.:10.675   3rd Qu.:59.15   3rd Qu.:139.75   3rd Qu.: 81163  
 Max.   :15.100   Max.   :67.30   Max.   :188.00   Max.   :566432  

In [149]:
# Structure of Data
str(states)

 num [1:50, 1:8] 3615 365 2212 2110 21198 ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:50] "Alabama" "Alaska" "Arizona" "Arkansas" ...
  ..$ : chr [1:8] "Population" "Income" "Illiteracy" "Life Exp" ...


## Creating Dataframes

Use the built-in R function **data.frame()** to pass vectors and arguements to create R Dataframes. The vectors a converted into columns in the R Dataframe.

In [150]:
# Creating a Dataframe from weather data
days <- c('Mon','Tue','Wed','Thu','Fri')
temp <- c(76.1, 82.3, 85.4, 78.9, 76.2)
rain <- c(TRUE, FALSE, FALSE, TRUE, TRUE)

In [151]:
df <- data.frame(days, temp, rain)

In [152]:
df

days temp rain 
1 Mon  76.1  TRUE
2 Tue  82.3 FALSE
3 Wed  85.4 FALSE
4 Thu  78.9  TRUE
5 Fri  76.2  TRUE

In [153]:
# Check structure
str(df)

'data.frame':	5 obs. of  3 variables:
 $ days: Factor w/ 5 levels "Fri","Mon","Thu",..: 2 4 5 3 1
 $ temp: num  76.1 82.3 85.4 78.9 76.2
 $ rain: logi  TRUE FALSE FALSE TRUE TRUE


In [154]:
summary(df)

  days        temp          rain        
 Fri:1   Min.   :76.10   Mode :logical  
 Mon:1   1st Qu.:76.20   FALSE:2        
 Thu:1   Median :78.90   TRUE :3        
 Tue:1   Mean   :79.78                  
 Wed:1   3rd Qu.:82.30                  
         Max.   :85.40                  

# <font color='red'>R Dataframe Indexing and Selection</font>

Similar to vectors and matrices, R Dataframes can be indexed and selected using bracket notation. 

In [155]:
df

days temp rain 
1 Mon  76.1  TRUE
2 Tue  82.3 FALSE
3 Wed  85.4 FALSE
4 Thu  78.9  TRUE
5 Fri  76.2  TRUE

In [156]:
# Get row and columns counts
nrow(df)
ncol(df)

[1] 5

[1] 3

In [157]:
# Get column names
colnames(df)

[1] "days" "temp" "rain"

In [158]:
# Get row names (may just return index)
rownames(df)

[1] "1" "2" "3" "4" "5"

In [159]:
# Use the bracket notation df[rows,columns]

# Everything from the first row
df[1,]

days temp rain
1 Mon  76.1 TRUE

In [160]:
# Everything from the first column

df[,1]

[1] Mon Tue Wed Thu Fri
Levels: Fri Mon Thu Tue Wed

NOTE: The R Dataframe 'df' shows you the data types of each of the columns. The 'days' column has been converted to a factor.

In [161]:
# Grab Friday data
df[5,]

days temp rain
5 Fri  76.2 TRUE

## Select using column names

This is where R Dataframes become very powerful. We can use column names to select data for the columns instead of having to remember numbers

In [162]:
# All of the rain values
df[,'rain']

[1]  TRUE FALSE FALSE  TRUE  TRUE

In [163]:
# First 5 rows for days and temps
df[1:5, c('days','temp')]

days temp
1 Mon  76.1
2 Tue  82.3
3 Wed  85.4
4 Thu  78.9
5 Fri  76.2

Use the '$' notation if you want all of the values of a particular column. This references the column name without the brackets

In [164]:
# Use $ to grab the rain data df.name$column.name
df$rain

[1]  TRUE FALSE FALSE  TRUE  TRUE

In [165]:
df$days

[1] Mon Tue Wed Thu Fri
Levels: Fri Mon Thu Tue Wed

The bracket notation can be used to grab the same information as the '$' notation, particularly if rows are not selected

In [166]:
# Grab the rain information
df['rain']

rain 
1  TRUE
2 FALSE
3 FALSE
4  TRUE
5  TRUE

In [167]:
# Grab the days information
df['days']

days
1 Mon 
2 Tue 
3 Wed 
4 Thu 
5 Fri

## Reference Cells

Individual cells can be referenced and converted into a new data frame using bracket notation

In [168]:
# Creating a vector from a referenced cell
vec <- df[[5,2]]
vec

[1] 76.2

In [169]:
# Making a new Dataframe from df
newdf <- df[1:3, 1:2]
newdf

days temp
1 Mon  76.1
2 Tue  82.3
3 Wed  85.4

In [170]:
#Changing the values of cells
df[[2, 'rain']] <- TRUE
df

days temp rain 
1 Mon  76.1  TRUE
2 Tue  82.3  TRUE
3 Wed  85.4 FALSE
4 Thu  78.9  TRUE
5 Fri  76.2  TRUE

## Creating new columns

Using brackets or the '$', new columns can easily be added from vectors or from combinations of other rows within the Dataframe

In [171]:
df

days temp rain 
1 Mon  76.1  TRUE
2 Tue  82.3  TRUE
3 Wed  85.4 FALSE
4 Thu  78.9  TRUE
5 Fri  76.2  TRUE

In [172]:
df$celcius <- (df$temp - 32) * 5/9
df

days temp rain  celcius 
1 Mon  76.1  TRUE 24.50000
2 Tue  82.3  TRUE 27.94444
3 Wed  85.4 FALSE 29.66667
4 Thu  78.9  TRUE 26.05556
5 Fri  76.2  TRUE 24.55556

In [173]:
df['over.80'] <- df['temp'] > 80
df

days temp rain  celcius  over.80
1 Mon  76.1  TRUE 24.50000 FALSE  
2 Tue  82.3  TRUE 27.94444  TRUE  
3 Wed  85.4 FALSE 29.66667  TRUE  
4 Thu  78.9  TRUE 26.05556 FALSE  
5 Fri  76.2  TRUE 24.55556 FALSE

## Filtering using subsetting conditions

Use the built-in R function **subset()** to grab a subset of values from an R Dataframe based of a set of conditions. For example, imagine grabbing the days where it rained (rain=TRUE).

In [174]:
# Grabbing a subset of data where rain==TRUE
subset(df, subset= rain==TRUE)

days temp rain celcius  over.80
1 Mon  76.1 TRUE 24.50000 FALSE  
2 Tue  82.3 TRUE 27.94444  TRUE  
4 Thu  78.9 TRUE 26.05556 FALSE  
5 Fri  76.2 TRUE 24.55556 FALSE

NOTE: The condition uses some sort of comparison operator. In the above example, the operator '==' pulls information where the condition is equal.

In [175]:
# Grab a subset where temperature was greater than 80 degrees
subset(df, temp > 80)

days temp rain  celcius  over.80
2 Tue  82.3  TRUE 27.94444 TRUE   
3 Wed  85.4 FALSE 29.66667 TRUE

NOTE: When using **subset()**, the R Dataframe is referenced as an arguement. That means that the column names DO NOT need to be input as a string.

## Conditional Subsetting

Multiple conditions can be used to subset a Dataframe using the operators & (and) and | (or) 

In [176]:
df

days temp rain  celcius  over.80
1 Mon  76.1  TRUE 24.50000 FALSE  
2 Tue  82.3  TRUE 27.94444  TRUE  
3 Wed  85.4 FALSE 29.66667  TRUE  
4 Thu  78.9  TRUE 26.05556 FALSE  
5 Fri  76.2  TRUE 24.55556 FALSE

In [177]:
subset(df, days != 'Wed' & temp < 80)

days temp rain celcius  over.80
1 Mon  76.1 TRUE 24.50000 FALSE  
4 Thu  78.9 TRUE 26.05556 FALSE  
5 Fri  76.2 TRUE 24.55556 FALSE

In [178]:
df[(df$days != 'Wed' & df$temp < 80),]

days temp rain celcius  over.80
1 Mon  76.1 TRUE 24.50000 FALSE  
4 Thu  78.9 TRUE 26.05556 FALSE  
5 Fri  76.2 TRUE 24.55556 FALSE

In [179]:
subset(df, days == 'Wed' | temp > 80)

days temp rain  celcius  over.80
2 Tue  82.3  TRUE 27.94444 TRUE   
3 Wed  85.4 FALSE 29.66667 TRUE

In [180]:
df[(df$days == 'Wed' | df$temp > 80),]

days temp rain  celcius  over.80
2 Tue  82.3  TRUE 27.94444 TRUE   
3 Wed  85.4 FALSE 29.66667 TRUE

## Ordering R Dataframes

The order of a R Dataframe can be sorted based on a specific column. Use the built-in R function **order()** to create a vector to sort the R Dataframe. Then pass the vector through to sort.

In [181]:
sorted.temp <- order(df$temp)

In [182]:
df[sorted.temp,]

days temp rain  celcius  over.80
1 Mon  76.1  TRUE 24.50000 FALSE  
5 Fri  76.2  TRUE 24.55556 FALSE  
4 Thu  78.9  TRUE 26.05556 FALSE  
2 Tue  82.3  TRUE 27.94444  TRUE  
3 Wed  85.4 FALSE 29.66667  TRUE

Let's follow what **order()** is doing to figure out how the R Dataframe is sorted

In [183]:
sorted.temp

[1] 1 5 4 2 3

Ok, so we are asking for indexed values of the ordered elements of sorted.temp (default=ascending) to pass through df to sort based on the temps. Use a negative value to sort in descending order

In [184]:
# Use the other column reference technique to sort in descending order
desc.temp <- order(-df['temp'])

In [185]:
df[desc.temp,]

days temp rain  celcius  over.80
3 Wed  85.4 FALSE 29.66667  TRUE  
2 Tue  82.3  TRUE 27.94444  TRUE  
4 Thu  78.9  TRUE 26.05556 FALSE  
5 Fri  76.2  TRUE 24.55556 FALSE  
1 Mon  76.1  TRUE 24.50000 FALSE

# <font color='red'>Merging and Binding R Dataframes</font>

Like we learned with matrices, we can add rows and columns using the built-in R functions **rbind()** and **cbind()**, respectively.

In [186]:
# Vector of Integers
c1 <- 1:10

In [187]:
# Vector of Characters - Use letters to pull from the alphabet
c2 <- letters[1:10]

In [188]:
df <- data.frame(col.name.1 = c1, col.name.2 = c2)

In [189]:
df

col.name.1 col.name.2
1   1         a         
2   2         b         
3   3         c         
4   4         d         
5   5         e         
6   6         f         
7   7         g         
8   8         h         
9   9         i         
10 10         j

In [190]:
# Adding rows using rbind()
df2 <- data.frame(col.name.1=2000, col.name.2='new')
rbind(df, df2)

col.name.1 col.name.2
1     1       a         
2     2       b         
3     3       c         
4     4       d         
5     5       e         
6     6       f         
7     7       g         
8     8       h         
9     9       i         
10   10       j         
11 2000       new

In [191]:
# Adding columns
times.2 <- df$col.name.1 * 2
cbind(df, times.2)

col.name.1 col.name.2 times.2
1   1         a           2     
2   2         b           4     
3   3         c           6     
4   4         d           8     
5   5         e          10     
6   6         f          12     
7   7         g          14     
8   8         h          16     
9   9         i          18     
10 10         j          20

## Merging Dataframes

Using the built-in R function **merge()**, we'll pull two Dataframes together using a common key between the two Dataframes

In [192]:
peanut.weight <- data.frame(
    name = I(c('Bailey','Bailey II','Wynne','Emery','Sullivan', 'Gregory')),
    weight = c(89.4, 92.3, 105.2, 103.1, 99.6, 89.1))
peanut.skins <- data.frame(
    name = I(c('Bailey','Bailey II','Wynne','Emery','Sullivan','Brantley')),
    skin = c('Tan', 'Tan', 'Pink', 'Pink', 'Tan', 'Red'))

In [193]:
peanut.weight

name      weight
1 Bailey     89.4 
2 Bailey II  92.3 
3 Wynne     105.2 
4 Emery     103.1 
5 Sullivan   99.6 
6 Gregory    89.1

In [194]:
peanut.skins

name      skin
1 Bailey    Tan 
2 Bailey II Tan 
3 Wynne     Pink
4 Emery     Pink
5 Sullivan  Tan 
6 Brantley  Red

In [195]:
merge(peanut.weight, peanut.skins, by.x = 'name', by.y = 'name')

name      weight skin
1 Bailey     89.4  Tan 
2 Bailey II  92.3  Tan 
3 Emery     103.1  Pink
4 Sullivan   99.6  Tan 
5 Wynne     105.2  Pink

In [196]:
peanuts <- merge(peanut.weight, peanut.skins, by.x = 'name', by.y = 'name', all = TRUE)
peanuts

name      weight skin
1 Bailey     89.4  Tan 
2 Bailey II  92.3  Tan 
3 Brantley     NA  Red 
4 Emery     103.1  Pink
5 Gregory    89.1  NA  
6 Sullivan   99.6  Tan 
7 Wynne     105.2  Pink

## Dealing with Missing Data

Missing data is a very important skill to know when working with Dataframes. Use the built-in R functions **any()** and **is.na()** in tandem to determine missing data points in a Dataframe

In [197]:
# Determine if there are missing data anywhere in peanuts
any(is.na(peanuts))

[1] TRUE

In [198]:
# Determine missing data points within columns
any(is.na(peanuts$weight))

[1] TRUE

In [199]:
any(is.na(peanuts$name))

[1] FALSE

In [200]:
# Delete selected missing data rows using '!' meaning 'NOT'
peanuts[!is.na(peanuts$weight),]

name      weight skin
1 Bailey     89.4  Tan 
2 Bailey II  92.3  Tan 
4 Emery     103.1  Pink
5 Gregory    89.1  NA  
6 Sullivan   99.6  Tan 
7 Wynne     105.2  Pink

In [201]:
# Replace the NA values with information
peanuts[is.na(peanuts)] <- 90.0

Warning message in `[<-.factor`(`*tmp*`, thisvar, value = 90):
"invalid factor level, NA generated"

NOTE: This should replace all NA values with 0 where the column data type is integer. Notice that the NA for Gregory under the column 'skin' is not replaced since this column is a factor

In [202]:
peanuts

name      weight skin
1 Bailey     89.4  Tan 
2 Bailey II  92.3  Tan 
3 Brantley   90.0  Red 
4 Emery     103.1  Pink
5 Gregory    89.1  NA  
6 Sullivan   99.6  Tan 
7 Wynne     105.2  Pink

In [203]:
# For selected columns
peanuts$skin[is.na(peanuts$skin)] <- 'Tan'

In [204]:
peanuts

name      weight skin
1 Bailey     89.4  Tan 
2 Bailey II  92.3  Tan 
3 Brantley   90.0  Red 
4 Emery     103.1  Pink
5 Gregory    89.1  Tan 
6 Sullivan   99.6  Tan 
7 Wynne     105.2  Pink

# <font color='red'>R List Basics</font>

We've covered vectors, matrices and Dataframes. This is the perfect opportunity to discuss list basics using the built-in R data structure **list()**

In [205]:
# Create a vector
v <- c(1,2,3,4,5)

# Create a matrix
m <- matrix(1:10, nrow = 2)

# Create a Dataframe
df <- women

In [206]:
v

[1] 1 2 3 4 5

In [207]:
m

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [208]:
df

height weight
1  58     115   
2  59     117   
3  60     120   
4  61     123   
5  62     126   
6  63     129   
7  64     132   
8  65     135   
9  66     139   
10 67     142   
11 68     146   
12 69     150   
13 70     154   
14 71     159   
15 72     164

## Creating Lists

Use the built-in R function **list()** to create a list data structure containing v, m and df

In [209]:
li <- list(v, m, df)

In [210]:
li

[[1]]
[1] 1 2 3 4 5

[[2]]
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

[[3]]
   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164

NOTE: There are index values to show you which element to reference to pull out v (1), m (2) or df (3). The index values can be changed to names, similar to Python keys in a dictionary

In [211]:
li <- list(sample_vec = v, sample_mat = m, sample_df = df)

In [212]:
li

$sample_vec
[1] 1 2 3 4 5

$sample_mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$sample_df
   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164

In [213]:
# Use brackets to select an object from the list using an index
li[1]

$sample_vec
[1] 1 2 3 4 5

In [214]:
# Use brackets to select an object by name
li['sample_vec']

$sample_vec
[1] 1 2 3 4 5

In [215]:
# Use double brackets to grab the elements from the index
li[['sample_vec']]

[1] 1 2 3 4 5

In [216]:
# Can use the '$' notation
li$sample_vec

[1] 1 2 3 4 5

In [217]:
# Use indexing to select elements within objects
li[['sample_vec']][1]

[1] 1

In [218]:
li[['sample_mat']]

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [219]:
li[['sample_mat']][1,]

[1] 1 3 5 7 9

In [220]:
li[['sample_mat']][1:2,1:2]

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [221]:
li[['sample_df']]['height']

height
1  58    
2  59    
3  60    
4  61    
5  62    
6  63    
7  64    
8  65    
9  66    
10 67    
11 68    
12 69    
13 70    
14 71    
15 72

## Combining Lists

Lists can hold other lists (nesting). Use the built-in R function combine **c()** to nest lists

In [222]:
# Doubling list
double_list <- c(li, li)

In [223]:
double_list

$sample_vec
[1] 1 2 3 4 5

$sample_mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$sample_df
   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164

$sample_vec
[1] 1 2 3 4 5

$sample_mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$sample_df
   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164

In [224]:
str(double_list)

List of 6
 $ sample_vec: num [1:5] 1 2 3 4 5
 $ sample_mat: int [1:2, 1:5] 1 2 3 4 5 6 7 8 9 10
 $ sample_df :'data.frame':	15 obs. of  2 variables:
  ..$ height: num [1:15] 58 59 60 61 62 63 64 65 66 67 ...
  ..$ weight: num [1:15] 115 117 120 123 126 129 132 135 139 142 ...
 $ sample_vec: num [1:5] 1 2 3 4 5
 $ sample_mat: int [1:2, 1:5] 1 2 3 4 5 6 7 8 9 10
 $ sample_df :'data.frame':	15 obs. of  2 variables:
  ..$ height: num [1:15] 58 59 60 61 62 63 64 65 66 67 ...
  ..$ weight: num [1:15] 115 117 120 123 126 129 132 135 139 142 ...


# End of Dataframes