![](logo.png)

# <font color='red'>For Loops</font>

A for loop allows us to iterate over an object (such as a vector) and we can then perform and execute blocks of codes for every loop we go through. The syntax for a for loop is:

**Basic Syntax:**

for (temporary_variable in object){
    # Execute some code at every loop
}


Let's go through some examples of for loops using vectors, matrices and dataframes

# <font color='red'>For Loops with Vectors</font>

We can loop through vector elements two different ways. The first is to consider a temporary variable with the use of **in** as a keyword comprehension arguement

In [2]:
# Create a vector
vec <- c(1,2,3,4,5)

In [3]:
for (temp_var in vec){
    print(temp_var)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


The other way would be to loop a numbered amount of times and then use indexing to control the number of loops while continuing to grab elements from the vector

In [4]:
for (i in 1:length(vec)){
    print(vec[i])
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


NOTE: The loop is controlled by the length or the number of elements in vec. This tells the loop to quit after the nth element. This could alternatively be an integer, but the integer must correspond to the total number of elements that need to be iterated over.

In [7]:
# Adding an integer instead of length produces an out-of-bounds element
for (i in 1:6){
    print(vec[i])
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] NA


# <font color='red'>For Loops with Matrices</font>

Similar to vectors, for loops can be designed to iterate through the elements of a matrix.

In [11]:
mat <- matrix(1:25, nrow=5, byrow = FALSE)
mat

[,1] [,2] [,3] [,4] [,5]
[1,] 1     6   11   16   21  
[2,] 2     7   12   17   22  
[3,] 3     8   13   18   23  
[4,] 4     9   14   19   24  
[5,] 5    10   15   20   25

In [12]:
for (num in mat){
    print(num)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10
[1] 11
[1] 12
[1] 13
[1] 14
[1] 15
[1] 16
[1] 17
[1] 18
[1] 19
[1] 20
[1] 21
[1] 22
[1] 23
[1] 24
[1] 25


NOTE: When the byrow = TRUE, the order of the printed elements changes

mat <- matrix(1:25, nrow=5, byrow = TRUE)

# <font color='red'>For Loops with Dataframes</font>

For loops can be designed to iterate through the elements of a dataframe.

In [14]:
df <- women

In [15]:
df

height weight
1  58     115   
2  59     117   
3  60     120   
4  61     123   
5  62     126   
6  63     129   
7  64     132   
8  65     135   
9  66     139   
10 67     142   
11 68     146   
12 69     150   
13 70     154   
14 71     159   
15 72     164

In [26]:
for (i in 1:length(df)){
    print(paste(sprintf('Individual %s',i),'Height =',df$height[i], 'and Weight = ',df$weight[i]))
}

#ncol() and length() return the number of columns in a dataframe

[1] "Individual 1 Height = 58 and Weight =  115"
[1] "Individual 2 Height = 59 and Weight =  117"


NOTE: the length does not return the length() (rows) of the dataframe. This is similar to ncol(). Use nrow() to return the number of rows to iterate over 

In [27]:
for (i in 1:nrow(df)){
    print(paste(sprintf('Individual %s',i),'Height =',df$height[i], 'and Weight = ',df$weight[i]))
}

[1] "Individual 1 Height = 58 and Weight =  115"
[1] "Individual 2 Height = 59 and Weight =  117"
[1] "Individual 3 Height = 60 and Weight =  120"
[1] "Individual 4 Height = 61 and Weight =  123"
[1] "Individual 5 Height = 62 and Weight =  126"
[1] "Individual 6 Height = 63 and Weight =  129"
[1] "Individual 7 Height = 64 and Weight =  132"
[1] "Individual 8 Height = 65 and Weight =  135"
[1] "Individual 9 Height = 66 and Weight =  139"
[1] "Individual 10 Height = 67 and Weight =  142"
[1] "Individual 11 Height = 68 and Weight =  146"
[1] "Individual 12 Height = 69 and Weight =  150"
[1] "Individual 13 Height = 70 and Weight =  154"
[1] "Individual 14 Height = 71 and Weight =  159"
[1] "Individual 15 Height = 72 and Weight =  164"


# <font color='red'>Nesting For Loops</font>

We can nest for loops inside one another; however, be careful when doing this, as every additional for loop nested inside another may cause a significant amount of additional time for your code to finish executing. 

In [28]:
mat

[,1] [,2] [,3] [,4] [,5]
[1,] 1     6   11   16   21  
[2,] 2     7   12   17   22  
[3,] 3     8   13   18   23  
[4,] 4     9   14   19   24  
[5,] 5    10   15   20   25

In [29]:
for (row in 1:nrow(mat)){
    for (col in 1:ncol(mat)){
        print(paste('The element at row:',row,'and col:',col,'is',mat[row,col]))
    }
}

[1] "The element at row: 1 and col: 1 is 1"
[1] "The element at row: 1 and col: 2 is 6"
[1] "The element at row: 1 and col: 3 is 11"
[1] "The element at row: 1 and col: 4 is 16"
[1] "The element at row: 1 and col: 5 is 21"
[1] "The element at row: 2 and col: 1 is 2"
[1] "The element at row: 2 and col: 2 is 7"
[1] "The element at row: 2 and col: 3 is 12"
[1] "The element at row: 2 and col: 4 is 17"
[1] "The element at row: 2 and col: 5 is 22"
[1] "The element at row: 3 and col: 1 is 3"
[1] "The element at row: 3 and col: 2 is 8"
[1] "The element at row: 3 and col: 3 is 13"
[1] "The element at row: 3 and col: 4 is 18"
[1] "The element at row: 3 and col: 5 is 23"
[1] "The element at row: 4 and col: 1 is 4"
[1] "The element at row: 4 and col: 2 is 9"
[1] "The element at row: 4 and col: 3 is 14"
[1] "The element at row: 4 and col: 4 is 19"
[1] "The element at row: 4 and col: 5 is 24"
[1] "The element at row: 5 and col: 1 is 5"
[1] "The element at row: 5 and col: 2 is 10"
[1] "The element at

# <font color='red'>For Loops with Lists</font>

Similar to vectors, for loops can be designed to iterate through the elements of a list.

In [30]:
li <- list(vec, mat, df)

In [31]:
for (i in li){
    print(i)
}

[1] 1 2 3 4 5
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    6   11   16   21
[2,]    2    7   12   17   22
[3,]    3    8   13   18   23
[4,]    4    9   14   19   24
[5,]    5   10   15   20   25
   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164


In [34]:
li

[[1]]
[1] 1 2 3 4 5

[[2]]
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    6   11   16   21
[2,]    2    7   12   17   22
[3,]    3    8   13   18   23
[4,]    4    9   14   19   24
[5,]    5   10   15   20   25

[[3]]
   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164

NOTE: There are differences between iterating across list elements and just printing the list. What if the first element of each of the list objects was iterated?

In [37]:
for (i in li){
    print(i[1])
}

[1] 1
[1] 1
   height
1      58
2      59
3      60
4      61
5      62
6      63
7      64
8      65
9      66
10     67
11     68
12     69
13     70
14     71
15     72


# <font color='red'>For Loops with IF, ELSE IF and ELSE statements</font>

Let's take a closer look at the example previously using a for loop with **if**, **else if** and **else**

In [38]:
lines <- c('Bailey','Bailey II','Sullivan','Emery') 
yield <- c(5100, 5600, 5200, 4900)
peanuts <- data.frame(lines,yield)

In [39]:
peanuts

lines     yield
1 Bailey    5100 
2 Bailey II 5600 
3 Sullivan  5200 
4 Emery     4900

In [40]:
# Just using if, else if and else
test <- min(peanuts$yield)

if (peanuts$yield[1] == test){
    print(paste(peanuts$lines[1],'has the lowest yield'))
}else if (peanuts$yield[2] == test){
    print(paste(peanuts$lines[2],'has the lowest yield')) 
}else if (peanuts$yield[3] == test){
    print(paste(peanuts$lines[3],'has the lowest yield'))
}else{
    print(paste(peanuts$lines[4],'has the lowest yield'))
}

[1] "Emery has the lowest yield"


In [41]:
# Use a for loop
for (i in 1:nrow(peanuts)){
    if (peanuts$yield[i] == test){
        print(paste(peanuts$lines[i],'has the lowest yield'))
    }
}

[1] "Emery has the lowest yield"
