![](Logo.png)

# <font color='red'>Week 3 - Introduction to NumPy Exercise</font>

This week focused on NumPy, a module or library in Python that processes arrays and matrices for mathematical compuatation. This exercise is designed to review the materials covered in the lecture

#### Import Shorthanded NumPy (Hint: np)

#### Create an array of 10 zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create and array of 10 ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create and array of 10 fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all of the even integers from 10 to 50

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3 x 3 matrix (array) with values ranging from 0 to 8

array([[0, 1, 2],
       <br>[3, 4, 5],
       <br>[6, 7, 8]])

#### Create a 3 x 3 matrix (matrix) with values ranging from 0 to 8

matrix([[0, 1, 2],
        <br>[3, 4, 5],
        <br>[6, 7, 8]])

#### Create a 3 x 3 identity matrix

array([[1., 0., 0.],
       <br>[0., 1., 0.],
       <br>[0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

array([0.89708448])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

np.random.randn(25)

#### Creat the following matrix:

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       <br>[0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       <br>[0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       <br>[0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       <br>[0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       <br>[0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       <br>[0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       <br>[0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       <br>[0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       <br>[0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1

np.linspace(0,1,20)

## NumPy Indexing and Selection

Use the provided matrix (array) to replicate the resulting matrix (array) output

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       <br>[ 6,  7,  8,  9, 10],
       <br>[11, 12, 13, 14, 15],
       <br>[16, 17, 18, 19, 20],
       <br>[21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE

array([[12, 13, 14, 15],
       <br>[17, 18, 19, 20],
       <br>[22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE

20

In [ ]:
# WRITE CODE HERE

array([[ 2],
       <br>[ 7],
       <br>[12]])

In [ ]:
# WRITE CODE HERE

array([21, 22, 23, 24, 25])

In [ ]:
# WRITE CODE HERE

array([[16, 17, 18, 19, 20],
       <br>[21, 22, 23, 24, 25]])

## Matrix Operations

Use the matrix > mat to detemine the following:

#### Calculate the sum of all the values in mat

325

#### Calculate the standard deviation of the values in mat

7.211102550927978

#### Calculate the sum of all of the columns in mat 

(Hint: Look up the **sum()** method, refer to the axis of the matrix [0,1])

array([55, 60, 65, 70, 75])